version: "3.9"

services:
  mariadb:
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "testo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user-password"

