version: '3.8'
services:

  db:
    image: hypriot/rpi-mysql
    environment:
     MYSQL_ROOT_PASSWORD: example123
    restart: always
    ports:
     - 3306:3306

  worker:
    build: ./server
    tty: true
    depends_on:
     - db
    restart: always
    ports:
     - 4444:4444

  web:
    image: httpd
    volumes:
     - ./app:/usr/local/apache2/htdocs/
    ports:
     - 8088:80
    restart: always
    depends_on:
     - worker

  admin:
    image: adminer
    ports:
     - 9000:8080
    links:
     - db
